
package com.it.sim.webservice.jdk.client;

import com.it.sim.webservice.jdk.server.EvalService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@SuppressWarnings({"SpellCheckingInspection", "HttpUrlsUsage"})
@WebServiceClient(name = "EvalServiceService", targetNamespace = "http://server.jdk.webservice.sim.it.com/", wsdlLocation = "http://localhost:49001/service/EvalService?wsdl")
public class EvalServiceService
    extends Service
{

    private final static URL EVALSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException EVALSERVICESERVICE_EXCEPTION;
    private final static QName EVALSERVICESERVICE_QNAME = new QName("http://server.jdk.webservice.sim.it.com/", "EvalServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:49001/service/EvalService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EVALSERVICESERVICE_WSDL_LOCATION = url;
        EVALSERVICESERVICE_EXCEPTION = e;
    }

    public EvalServiceService() {
        super(__getWsdlLocation(), EVALSERVICESERVICE_QNAME);
    }

    public EvalServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EVALSERVICESERVICE_QNAME, features);
    }

    public EvalServiceService(URL wsdlLocation) {
        super(wsdlLocation, EVALSERVICESERVICE_QNAME);
    }

    public EvalServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EVALSERVICESERVICE_QNAME, features);
    }

    public EvalServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EvalServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EvalService
     */
    @WebEndpoint(name = "EvalServicePort")
    public com.it.sim.webservice.jdk.server.EvalService getEvalServicePort() {
        return super.getPort(new QName("http://server.jdk.webservice.sim.it.com/", "EvalServicePort"), com.it.sim.webservice.jdk.server.EvalService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EvalService
     */
    @WebEndpoint(name = "EvalServicePort")
    public com.it.sim.webservice.jdk.server.EvalService getEvalServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.jdk.webservice.sim.it.com/", "EvalServicePort"), EvalService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EVALSERVICESERVICE_EXCEPTION!= null) {
            throw EVALSERVICESERVICE_EXCEPTION;
        }
        return EVALSERVICESERVICE_WSDL_LOCATION;
    }

}
