
package com.it.sim.webservice.jdk.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@SuppressWarnings("ALL")
@WebService(name = "EvalService", targetNamespace = "http://server.jdk.webservice.sim.it.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EvalService {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://server.jdk.webservice.sim.it.com/", className = "com.it.sim.webservice.jdk.server.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://server.jdk.webservice.sim.it.com/", className = "com.it.sim.webservice.jdk.server.AddResponse")
    @Action(input = "http://server.jdk.webservice.sim.it.com/EvalService/addRequest", output = "http://server.jdk.webservice.sim.it.com/EvalService/addResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sub", targetNamespace = "http://server.jdk.webservice.sim.it.com/", className = "com.it.sim.webservice.jdk.server.Sub")
    @ResponseWrapper(localName = "subResponse", targetNamespace = "http://server.jdk.webservice.sim.it.com/", className = "com.it.sim.webservice.jdk.server.SubResponse")
    @Action(input = "http://server.jdk.webservice.sim.it.com/EvalService/subRequest", output = "http://server.jdk.webservice.sim.it.com/EvalService/subResponse")
    public int sub(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
