server:
  port: 39001
spring:
  jackson:
    time-zone: GMT+8
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: test-group-id
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer # 默认: org.apache.kafka.common.serialization.StringSerializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # 默认(String 需要自己转对象): org.apache.kafka.common.serialization.StringSerializer
    admin:
      client-id: 10001

logging:
  file:
    path: data/log/kafka
#  pattern:
#    console: %d{yyyy-MM-dd hh:mm:ss} [%thread] %-5level %logger{50} - %msg%n
#    file: %d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} === - %msg%n