
package com.it.sim.webservice.jdk2.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@SuppressWarnings({"HttpUrlsUsage", "UnnecessaryModifier"})
@WebService(name = "IHelloService", targetNamespace = "http://it.com")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IHelloService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://it.com/IHelloService/sayHelloRequest", output = "http://it.com/IHelloService/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "ret", partName = "ret")
    @Action(input = "http://it.com/IHelloService/sayHiRequest", output = "http://it.com/IHelloService/sayHiResponse")
    public String sayHi(
        @WebParam(name = "name", partName = "name")
        String name);

}
