spring:
  application:
    name: eureka-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      #      naming:
      #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update # none: 禁用; create: 启动时重建; create-drop: 启动时重建, 退出时删除;update 首次初始化schema, 之后更新schema, 已经不存在字段对应的数据不会被删除;validate 执行验证, 不创建新表, 可以加新值
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
###服务端口号
server:
  port: 8888
###eureka 基本信息配置
eureka:
  instance:
###注册到eurekaip地址
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      ###因为自己是为注册中心，不需要自己注册自己
    register-with-eureka: false
    ###因为自己是为注册中心，不需要检索服务
    fetch-registry: false