#MQTT-服务端地址
server:
  port: 20627
publish:
  mqtt:
    host: tcp://127.0.0.1:1883
    username: admin
    password: wg@123456
    cleanSession: false #MQTT-是否清理session
    clientId: mqtt_publish #MQTT-当前客户端的唯一标识
    defaultTopic: 测试 #当前客户端的默认主题(大多数时候没什么用)
    timeout: 1000 #发送超时时间
    keepalive: 10 #心跳时间
    connectionTimeout: 3000 #连接超时时间
