<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions name="IHelloServiceService" targetNamespace="http://service.cxf.it.com/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://service.cxf.it.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
<xs:schema elementFormDefault="unqualified" targetNamespace="http://service.cxf.it.com/" version="1.0" xmlns:tns="http://service.cxf.it.com/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="sayX" type="tns:sayX"/>
<xs:element name="sayXResponse" type="tns:sayXResponse"/>
<xs:complexType name="sayX">
<xs:sequence>
<xs:element minOccurs="0" name="arg0" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="sayXResponse">
<xs:sequence>
<xs:element minOccurs="0" name="return" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:schema>
  </wsdl:types>
  <wsdl:message name="sayXResponse">
    <wsdl:part element="tns:sayXResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="sayX">
    <wsdl:part element="tns:sayX" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="IHelloService">
    <wsdl:operation name="sayX">
      <wsdl:input message="tns:sayX" name="sayX">
    </wsdl:input>
      <wsdl:output message="tns:sayXResponse" name="sayXResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="IHelloServiceServiceSoapBinding" type="tns:IHelloService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="sayX">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="sayX">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="sayXResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="IHelloServiceService">
    <wsdl:port binding="tns:IHelloServiceServiceSoapBinding" name="IHelloServicePort">
      <soap:address location="http://127.0.0.1:9999/hihi"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>