package com.it.webservice.cxf.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.4
 * 2024-01-25T21:20:19.391+08:00
 * Generated source version: 3.5.4
 *
 */
@WebServiceClient(name = "IHelloServiceService",
                  wsdlLocation = "http://127.0.0.1:9999/hihi?wsdl",
                  targetNamespace = "http://service.cxf.webservice.it.com/")
public class IHelloServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.cxf.webservice.it.com/", "IHelloServiceService");
    public final static QName IHelloServicePort = new QName("http://service.cxf.webservice.it.com/", "IHelloServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:9999/hihi?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IHelloServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:9999/hihi?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IHelloServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IHelloServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IHelloServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public IHelloServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IHelloServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IHelloServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IHelloService
     */
    @WebEndpoint(name = "IHelloServicePort")
    public IHelloService getIHelloServicePort() {
        return super.getPort(IHelloServicePort, IHelloService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHelloService
     */
    @WebEndpoint(name = "IHelloServicePort")
    public IHelloService getIHelloServicePort(WebServiceFeature... features) {
        return super.getPort(IHelloServicePort, IHelloService.class, features);
    }

}
