package com.it.webservice.cxf.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.4
 * 2024-01-25T21:20:19.364+08:00
 * Generated source version: 3.5.4
 *
 */
@WebService(targetNamespace = "http://service.cxf.webservice.it.com/", name = "IHelloService")
@XmlSeeAlso({ObjectFactory.class})
public interface IHelloService {

    @WebMethod
    @RequestWrapper(localName = "sayX", targetNamespace = "http://service.cxf.webservice.it.com/", className = "com.it.webservice.cxf.client.SayX")
    @ResponseWrapper(localName = "sayXResponse", targetNamespace = "http://service.cxf.webservice.it.com/", className = "com.it.webservice.cxf.client.SayXResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayX(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
