server:
  port: 29090
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jiangxin?useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      #      naming:
      #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update # none: 禁用; create: 启动时重建; create-drop: 启动时重建, 退出时删除;update 首次初始化schema, 之后更新schema, 已经不存在字段对应的数据不会被删除;validate 执行验证, 不创建新表, 可以加新值
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password: 1234567890
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:
  file:
    path: data/log
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-underline: false
secret: abc@123
upload_path: D:\workspace\TemplateBoot\JiangXin\data\upload
serveHost: 127.0.0.1