server:
  port: 9091
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/template_boot?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update # none 禁用; create 启动时重建 schema; create-drop 启动时重建 schema, 退出时删除 schema;update 首次初始化schema, 之后更新schema, 已经不存在字段对应的数据不会被删除;validate 执行验证, 不创建新表, 可以加新值
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mail:
    host: xxx@qq.com
    username: xxx
    password: xxx
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 1
  cache:
    redis:
      time-to-live: 600000
templateBoot:
  testPort: 3666
logging:
  file:
    path: data/log/api
#  pattern:
#    console: %d{yyyy-MM-dd hh:mm:ss} [%thread] %-5level %logger{50} - %msg%n
#    file: %d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} === - %msg%n
mybatis-plus:
  mapper-locations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis:
  #如果使用了mybatis-plus，需要把classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml配置到这里：mybatis-plus.mapper-locations
  mapper-locations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
  model:
    pack: com.it.boot.entity  #扫描用于创建表的对象的包名，多个包用“,”隔开
  database:
    type: mysql #数据库类型 目前只支持mysql
  table:
    auto: update
secret: abc@123