###服务启动端口号
server:
  port: 8801
###服务名称(服务注册到eureka名称)
spring:
  application:
     name: cloud-user
###服务注册到eureka地址
eureka:
  # instance:
    # prefer-ip-address: true
    # instance-id: 192.168.3.2:${server.port}
    # hostname: localhost
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka
###因为该应用为注册中心
    register-with-eureka: true
###是否需要从eureka上获取注册信息
    fetch-registry: true