server:
  port: 39100
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oa?useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      #      naming:
      #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update # none: 禁用; create: 启动时重建; create-drop: 启动时重建, 退出时删除;update 首次初始化schema, 之后更新schema, 已经不存在字段对应的数据不会被删除;validate 执行验证, 不创建新表, 可以加新值
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password: 1234567890
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 100MB #最大请求文件的大小
      max-file-size: 20MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入
logging:
  file:
    path: data/log
  #  pattern: #日志文件输出格式
  #    file: %d{yyyy-MM-dd}
  #    console:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
#    root: error

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #    map-underscore-to-camel-case: false
  global-config:
    db-config:
      table-underline: false
