server:
  port: 20620
spring:
  application:
    name:
      TestSpringdoc
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

springdoc:
  api-docs:
    path: /v3/api-docs # 自动生成的 OpenAPI 3.0 规范的 JSON 文件访问路径（默认值，可省略）
  swagger-ui:
    path: /swagger-ui.html # Swagger UI 的访问路径（默认是 /swagger-ui.html）
    tags-sorter: alpha  # 按字母顺序排序接口标签
    filter: true                # 启用搜索框过滤
  show-actuator: true           # 包含 Actuator 端点的文档