# 使用官方的 Maven 镜像作为基础镜像
FROM maven:3.6.3-jdk-8 AS build
# 将当前目录设置为工作目录
WORKDIR /app
# 将本地 Maven 项目的 pom.xml 和 src 目录复制到 Docker 容器的 /app 目录下
COPY pom.xml /app
COPY src /app/src
# 在 Docker 容器中构建 Maven 项目
RUN mvn clean package

# 使用一个轻量级的 JDK 镜像作为基础镜像
FROM openjdk:8-jre-slim
# 设置工作目录
WORKDIR /app
# 将 Maven 容器中的 target/*.jar 复制到 Docker 容器的 /app 目录下
COPY --from=build /app/target/*.jar /app/app.jar
# 暴露 8080 端口，Spring Boot 应用默认使用 8080 端口
EXPOSE 8080
# 在容器启动时运行 jar 包
CMD ["java", "-jar", "app.jar"]

# docker build -t springboot-demo .
# docker run -p 8080:8080 springboot-demo
